test:
  callback_url:
  redis:
    host: localhost
    port: 6379

development:
  callback_url:
  redis:
    host: localhost
    port: 6379

production:
  callback_url:
  redis:
    host: localhost
    port: 6379
